test:
  protect:
    user: ''
    pwd: ''
  secret_key_base: '13b6f07e65f8b5d89c9b6071c3079f72071cffb7282df878110dee51e9db579241d7e8583c87ec56ca129c237748edb361f6d1f44dad9d254626d7d62912f8e7'
  devise_secret_key: '4daa3140cee6a1305a3d81b3575f34be268b51dbed051a04afe5d9ae867e33359bc3236d03add96fcb2dbeb893f80dbd6be024aa4a53b8033bc3052a82cb10a1'
  google:
    api: 'test'
    id: 'test'
    secret: 'test'
  algolia:
    app_id: 'test'
    api_key: 'test'
    pub_key: 'test'
  frontend_host: 'http://test.host.com'
  redis_url: redis://localhost:6379

development:
  protect:
    user: ''
    pwd: ''
  secret_key_base: '1f17f4615455f607b7c9a80c6f1f2932028ceed1420ea8f8987ec33eb7caf18350423d45f88053b8bd2285787579884c3211343b6329b2184ee3cf6fb1019c85'
  devise_secret_key: '393fb72b9c78c6bebb69e61ad5acdee02a685572fe0456b0a3c197ea6cb7835b4e5696ce3efd7f5c35d1b3eeb350bf3796c2a666892d00872046daa7d3e37105'
  google:
    api: <%= ENV['GOOGLE_API'] %>
    id: <%= ENV['GOOGLE_ID'] %>
    secret: <%= ENV['GOOGLE_SECRET'] %>
  algolia:
    app_id: <%= ENV['ALGOLIA_ID'] || 'WOULDNTYOU' %>
    api_key: <%= ENV['ALGOLIA_KEY'] || 'LIKETOKNOW' %>
    pub_key: <%= ENV['ALGOLIA_PUB'] || '...' %>
  frontend_host: <%= ENV['FRONTEND_HOST'] || 'http://localhost:3000' %>
  redis_url: redis://localhost:6379

production:
  protect:
    user: "<%= ENV['ACCESS_UNAME'] %>"
    pwd: "<%= ENV['ACCESS_PWD'] %>"
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['DEVISE_KEY'] %>
  google: &google_secret
    api: <%= ENV['GOOGLE_API'] %>
    id: <%= ENV['GOOGLE_ID'] %>
    secret: <%= ENV['GOOGLE_SECRET'] %>
  algolia: &algolia
    app_id: <%= ENV['ALGOLIA_ID'] %>
    api_key: <%= ENV['ALGOLIA_KEY'] %>
    pub_key: <%= ENV['ALGOLIA_PUB'] %>
  frontend_host: <%= ENV['FRONTEND_HOST'] %>
  redis_url: <%= ENV['REDIS_PROVIDER'] && ENV[ENV['REDIS_PROVIDER']] %>

staging:
  protect:
    user: "<%= ENV['ACCESS_UNAME'] %>"
    pwd: "<%= ENV['ACCESS_PWD'] %>"
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['DEVISE_KEY'] %>
  google: *google_secret
  algolia: *algolia
  frontend_host: <%= ENV['FRONTEND_HOST'] %>
  redis_url: <%= ENV['REDIS_PROVIDER'] && ENV[ENV['REDIS_PROVIDER']] %>
